{% set name = "foonathan-memory" %}
{% set version = "0.7.3" %}
{% set major_version = version.split('.')[0] %}
{% set minor_version = version.split('.')[1] %}
{% set patch_version = version.split('.')[2] %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/foonathan/memory/archive/refs/tags/v{{ major_version }}.{{ minor_version }}-{{ patch_version }}.tar.gz
    sha256: 4203d15db22a94a3978eeb1afb59a37d35c57c0f148733f0f1a53a6281cb74dd
    patches:
      - add-comp-base.patch
      - fix-crosscompile.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - ninja
    - cmake

test:
  commands:
    - test -f ${PREFIX}/lib/libfoonathan_memory-{{ version }}${SHLIB_EXT}  # [not win]
    - if exist %LIBRARY_PREFIX%\\lib\\foonathan_memory-{{ version }}.lib (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\\bin\\foonathan_memory-{{ version }}.dll (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/foonathan/memory
  license: Zlib
  license_file: LICENSE
  summary: |
    STL compatible C++ memory allocator library using a new RawAllocator concept that is similar
    to an Allocator but easier to use and write.

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - Tobias-Fischer
