{% set name = "foonathan-memory" %}
{% set version = "0.6.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/foonathan/memory/archive/refs/tags/v0.6-2.tar.gz
    sha256: cf302578f3b6721707b8428fd9b97182ada1970ce56f8881ea0b3390b97e66e3
    patches:
      - fix-windows-install.patch
      - visibility-control.patch
      - add-comp-base.patch 

build:
  number: 2
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}              # [not win]
    - {{ compiler('c') }}                # [not win]
    - ninja
    - cmake

test:
  commands:
    - test -f ${PREFIX}/lib/libfoonathan_memory-0.6.2${SHLIB_EXT}  # [not win]
    - if exist %LIBRARY_PREFIX%\\lib\\foonathan_memory-0.6.2.lib (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\\bin\\foonathan_memory-0.6.2.dll (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/foonathan/memory
  license: zlib
  license_file: LICENSE
  summary: |
    STL compatible C++ memory allocator library using a new RawAllocator concept that is similar
    to an Allocator but easier to use and write.

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
